/**
 * generate-fzk-brep-fixtures.ts — §WEB-CAD#62
 *
 * Generate BrepSnapshot fixture JSONs for each FZK-Haus element type by running
 * the parametric builders with canonical FZK parameters, then extracting vertex
 * clouds + face normals from the resulting THREE.js geometry.
 *
 * Usage:
 *   bun scripts/generate-fzk-brep-fixtures.ts
 *
 * Writes:
 *   web/test/fixtures/fzk-brep-roof.json
 *   web/test/fixtures/fzk-brep-wall.json
 *   web/test/fixtures/fzk-brep-slab.json
 *   web/test/fixtures/fzk-brep-door.json
 *   web/test/fixtures/fzk-brep-window.json
 *   web/test/fixtures/fzk-brep-stair.json
 *
 * These fixtures are re-generated when builder math changes. Commit updated
 * fixtures alongside the builder change — the comparison gate then catches
 * regressions in subsequent runs.
 *
 * Parameters come from the existing fzk-haus-roof-target.json (which was derived
 * from the AC20-FZK-Haus.ifc reference geometry — 12×10m footprint, 30° pitch,
 * 0.5m overhang).
 */

// Stub browser globals so builder modules load in Node/Bun context.
// Must be set BEFORE any module imports that reference window/document/etc.
(globalThis as unknown as Record<string, unknown>).window = globalThis;
(globalThis as unknown as Record<string, unknown>).document = { createElement: () => ({}) };

import { writeFileSync } from "node:fs";
import path from "node:path";
import * as THREE from "three";

// Builder imports
import { buildRoof, buildWall, buildSlab, buildStair } from "../web/src/tools/structural";
import { buildDoor, buildWindow } from "../web/src/tools/openings";
import { objectToBrepSnapshot, geometryToBrepSnapshot } from "../web/src/test/mesh-to-brep-snapshot";

const FIXTURE_DIR = path.resolve(import.meta.dir, "../web/test/fixtures");

function writeFixture(name: string, data: unknown) {
  const out = path.join(FIXTURE_DIR, `fzk-brep-${name}.json`);
  writeFileSync(out, JSON.stringify({ schema_version: 1, source: "generated by generate-fzk-brep-fixtures.ts", ...data as object }, null, 2));
  console.log(`Wrote ${out}`);
}

// ── Roof (12×10m footprint, 30° pitch, 0.5m overhang) ─────────────────────────
{
  const { mesh } = buildRoof({ x: -6, y: -5 }, { x: 6, y: 5 }, { pitchDeg: 30, overhang: 0.5 });
  const snap = objectToBrepSnapshot(mesh);
  writeFixture("roof", {
    params: { p0: { x: -6, y: -5 }, p1: { x: 6, y: 5 }, pitchDeg: 30, overhang: 0.5 },
    snapshot: snap,
  });
}

// ── Wall (FZK outer wall: length ~12m, height 2.7m, along X axis) ────────────
{
  const { mesh } = buildWall({ x: -6, y: 0 }, { x: 6, y: 0 }, 2.7);
  mesh.updateMatrixWorld(true);
  const snap = geometryToBrepSnapshot(mesh.geometry, mesh.matrixWorld);
  writeFixture("wall", {
    params: { a: { x: -6, y: 0 }, b: { x: 6, y: 0 }, height: 2.7 },
    snapshot: snap,
  });
}

// ── Slab (ground floor 12×10m) ────────────────────────────────────────────────
{
  const { mesh } = buildSlab({ x: -6, y: -5 }, { x: 6, y: 5 });
  mesh.updateMatrixWorld(true);
  const snap = geometryToBrepSnapshot(mesh.geometry, mesh.matrixWorld);
  writeFixture("slab", {
    params: { a: { x: -6, y: -5 }, b: { x: 6, y: 5 } },
    snapshot: snap,
  });
}

// ── Door (standard single door) ───────────────────────────────────────────────
{
  const { mesh } = buildDoor({ x: 0, y: 0 });
  mesh.updateMatrixWorld(true);
  const snap = geometryToBrepSnapshot(mesh.geometry, mesh.matrixWorld);
  writeFixture("door", {
    params: { p: { x: 0, y: 0 } },
    snapshot: snap,
  });
}

// ── Window (standard window with sill) ────────────────────────────────────────
{
  const { mesh } = buildWindow({ x: 0, y: 0 });
  mesh.updateMatrixWorld(true);
  const snap = geometryToBrepSnapshot(mesh.geometry, mesh.matrixWorld);
  writeFixture("window", {
    params: { p: { x: 0, y: 0 } },
    snapshot: snap,
  });
}

// ── Stair (FZK-Haus: standard straight stair, 1m wide) ───────────────────────
{
  const { group } = buildStair({ x: 0, y: 0 }, { x: 3, y: 2 }, { width: 1.0 });
  const snap = objectToBrepSnapshot(group);
  writeFixture("stair", {
    params: { a: { x: 0, y: 0 }, b: { x: 3, y: 2 }, width: 1.0 },
    snapshot: snap,
  });
}

console.log("Done.");
