// brep-fzk-invariant.test.ts — §WEB-CAD#62
//
// Per-vertex + per-face-normal Brep comparison gate for FZK-Haus parametric builders.
// Runs each builder with canonical FZK parameters, compares the resulting tessellated
// geometry against the golden BrepSnapshot fixture within 1mm tolerance.
//
// Fixtures are generated by: bun --preload web/test/setup-dom.ts scripts/generate-fzk-brep-fixtures.ts
// Re-run and commit updated fixtures whenever builder math changes intentionally.
//
// Tolerance: 1e-3 m (1 mm) vertex distance, 1e-3 normal angular deviation (≈0.057°).

import { describe, test, expect } from "bun:test";
import { buildRoof, buildWall, buildSlab, buildStair } from "../src/tools/structural";
import { buildDoor, buildWindow } from "../src/tools/openings";
import {
  objectToBrepSnapshot,
  geometryToBrepSnapshot,
} from "../src/test/mesh-to-brep-snapshot";
import { compareBrepSnapshot } from "../src/test/brep-compare";

import roofFixture   from "./fixtures/fzk-brep-roof.json";
import wallFixture   from "./fixtures/fzk-brep-wall.json";
import slabFixture   from "./fixtures/fzk-brep-slab.json";
import doorFixture   from "./fixtures/fzk-brep-door.json";
import windowFixture from "./fixtures/fzk-brep-window.json";
import stairFixture  from "./fixtures/fzk-brep-stair.json";

const VERTEX_TOL = 1e-3;
const NORMAL_TOL = 1e-3;

// ── Roof ───────────────────────────────────────────────────────────────────────
describe("Brep gate: buildRoof (FZK 12×10m, 30°, 0.5m overhang)", () => {
  const { mesh } = buildRoof({ x: -6, y: -5 }, { x: 6, y: 5 }, { pitchDeg: 30, overhang: 0.5 });
  const actual = objectToBrepSnapshot(mesh);
  const ref = roofFixture.snapshot as typeof actual;
  const result = compareBrepSnapshot(actual, ref, VERTEX_TOL, NORMAL_TOL);

  test("vertex count matches fixture", () => {
    expect(actual.vertCount).toBe(ref.vertCount);
  });

  test("face count matches fixture", () => {
    expect(actual.faceCount).toBe(ref.faceCount);
  });

  test("max vertex delta ≤ 1mm", () => {
    expect(result.max_vertex_delta_m).toBeLessThanOrEqual(VERTEX_TOL);
  });

  test("max normal deviation ≤ 1e-3", () => {
    expect(result.max_normal_angular_dev).toBeLessThanOrEqual(NORMAL_TOL);
  });

  test("no vertex failures", () => {
    expect(result.vertex_failures).toHaveLength(0);
  });
});

// ── Wall ───────────────────────────────────────────────────────────────────────
describe("Brep gate: buildWall (FZK 12m outer wall, h=2.7m)", () => {
  const { mesh } = buildWall({ x: -6, y: 0 }, { x: 6, y: 0 }, 2.7);
  mesh.updateMatrixWorld(true);
  const actual = geometryToBrepSnapshot(mesh.geometry, mesh.matrixWorld);
  const ref = wallFixture.snapshot as typeof actual;
  const result = compareBrepSnapshot(actual, ref, VERTEX_TOL, NORMAL_TOL);

  test("vertex count matches fixture", () => {
    expect(actual.vertCount).toBe(ref.vertCount);
  });

  test("max vertex delta ≤ 1mm", () => {
    expect(result.max_vertex_delta_m).toBeLessThanOrEqual(VERTEX_TOL);
  });

  test("max normal deviation ≤ 1e-3", () => {
    expect(result.max_normal_angular_dev).toBeLessThanOrEqual(NORMAL_TOL);
  });
});

// ── Slab ───────────────────────────────────────────────────────────────────────
describe("Brep gate: buildSlab (FZK ground floor 12×10m)", () => {
  const { mesh } = buildSlab({ x: -6, y: -5 }, { x: 6, y: 5 });
  mesh.updateMatrixWorld(true);
  const actual = geometryToBrepSnapshot(mesh.geometry, mesh.matrixWorld);
  const ref = slabFixture.snapshot as typeof actual;
  const result = compareBrepSnapshot(actual, ref, VERTEX_TOL, NORMAL_TOL);

  test("vertex count matches fixture", () => {
    expect(actual.vertCount).toBe(ref.vertCount);
  });

  test("max vertex delta ≤ 1mm", () => {
    expect(result.max_vertex_delta_m).toBeLessThanOrEqual(VERTEX_TOL);
  });
});

// ── Door ───────────────────────────────────────────────────────────────────────
describe("Brep gate: buildDoor (standard)", () => {
  const { mesh } = buildDoor({ x: 0, y: 0 });
  mesh.updateMatrixWorld(true);
  const actual = geometryToBrepSnapshot(mesh.geometry, mesh.matrixWorld);
  const ref = doorFixture.snapshot as typeof actual;
  const result = compareBrepSnapshot(actual, ref, VERTEX_TOL, NORMAL_TOL);

  test("vertex count matches fixture", () => {
    expect(actual.vertCount).toBe(ref.vertCount);
  });

  test("max vertex delta ≤ 1mm", () => {
    expect(result.max_vertex_delta_m).toBeLessThanOrEqual(VERTEX_TOL);
  });
});

// ── Window ─────────────────────────────────────────────────────────────────────
describe("Brep gate: buildWindow (standard)", () => {
  const { mesh } = buildWindow({ x: 0, y: 0 });
  mesh.updateMatrixWorld(true);
  const actual = geometryToBrepSnapshot(mesh.geometry, mesh.matrixWorld);
  const ref = windowFixture.snapshot as typeof actual;
  const result = compareBrepSnapshot(actual, ref, VERTEX_TOL, NORMAL_TOL);

  test("vertex count matches fixture", () => {
    expect(actual.vertCount).toBe(ref.vertCount);
  });

  test("max vertex delta ≤ 1mm", () => {
    expect(result.max_vertex_delta_m).toBeLessThanOrEqual(VERTEX_TOL);
  });
});

// ── Stair ──────────────────────────────────────────────────────────────────────
describe("Brep gate: buildStair (FZK standard, 1m wide)", () => {
  const { group } = buildStair({ x: 0, y: 0 }, { x: 3, y: 2 }, { width: 1.0 });
  const actual = objectToBrepSnapshot(group);
  const ref = stairFixture.snapshot as typeof actual;
  const result = compareBrepSnapshot(actual, ref, VERTEX_TOL, NORMAL_TOL);

  test("vertex count matches fixture", () => {
    expect(actual.vertCount).toBe(ref.vertCount);
  });

  test("max vertex delta ≤ 1mm", () => {
    expect(result.max_vertex_delta_m).toBeLessThanOrEqual(VERTEX_TOL);
  });
});
