// vault-corpus-query.ts — text + facet search over the static vault manifest (#52).
//
// The manifest (web/public/vault/manifest.json) is a pre-baked index of all
// buildings in the vault, with DCS (Data Coverage Score = distinct data-type slots
// covered / total expected) and per-building facets. It is generated by
// scripts/vault-prebake.mjs and committed as a static asset.
//
// Query ranking: cosine-style text match over slug + name + type + country + era,
// multiplied by DCS (more complete buildings rank higher at equal relevance).
// Facet filters narrow before scoring.

/** One entry in vault/manifest.json. */
export interface VaultBuildingMeta {
  slug: string;
  name: string;
  qid: string | null;
  era: string | null;
  year: number | null;
  type: string | null;
  country: string | null;
  record_count: number;
  /** Data Coverage Score in [0, 1]. Higher = more complete vault data. */
  dcs: number;
  facets: string[];
}

export interface VaultManifest {
  schema_version: number;
  count: number;
  buildings: VaultBuildingMeta[];
}

export interface VaultCorpusResult {
  building: VaultBuildingMeta;
  /** Relevance × DCS composite score in [0, 1]. */
  score: number;
  /** Text fields that matched the query, for UI highlighting. */
  matchedFields: string[];
}

export interface VaultFacetFilter {
  era?: string;
  type?: string;
  country?: string;
  facet?: string;
}

// ── Manifest loading (cached) ─────────────────────────────────────────────────

let _manifestCache: VaultManifest | null = null;
let _manifestFetch: Promise<VaultManifest> | null = null;

function manifestUrl(): string {
  const base = (import.meta.env?.BASE_URL as string | undefined) ?? "/WEB-CAD/";
  return `${base}vault/manifest.json`.replace(/\/+/g, "/").replace(":/", "://");
}

export async function fetchVaultManifest(): Promise<VaultManifest> {
  if (_manifestCache) return _manifestCache;
  if (_manifestFetch) return _manifestFetch;
  _manifestFetch = fetch(manifestUrl())
    .then((r) => {
      if (!r.ok) throw new Error(`vault manifest HTTP ${r.status}`);
      return r.json() as Promise<VaultManifest>;
    })
    .then((m) => {
      _manifestCache = m;
      _manifestFetch = null;
      return m;
    });
  return _manifestFetch;
}

// ── Text matching ──────────────────────────────────────────────────────────────

function normalize(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9\s]/g, " ").trim();
}

function tokenize(s: string): string[] {
  return normalize(s).split(/\s+/).filter((t) => t.length > 1);
}

/** Score how well a building matches a query. Returns 0 if no match. */
function textScore(b: VaultBuildingMeta, queryTokens: string[]): { score: number; matched: string[] } {
  if (queryTokens.length === 0) return { score: 1, matched: [] };

  const fields = [
    { text: b.name,    weight: 3.0 },
    { text: b.slug,    weight: 2.0 },
    { text: b.country ?? "", weight: 1.5 },
    { text: b.type    ?? "", weight: 1.5 },
    { text: b.era     ?? "", weight: 1.0 },
    { text: b.facets.join(" "), weight: 1.0 },
    { text: String(b.year ?? ""), weight: 0.5 },
  ];

  let totalWeight = 0;
  let hitWeight = 0;
  const matched: string[] = [];

  for (const { text, weight } of fields) {
    if (!text) continue;
    const fieldTokens = new Set(tokenize(text));
    totalWeight += weight;
    let anyHit = false;
    for (const qt of queryTokens) {
      if (fieldTokens.has(qt) || text.toLowerCase().includes(qt)) {
        anyHit = true;
        if (!matched.includes(text)) matched.push(text);
      }
    }
    if (anyHit) hitWeight += weight;
  }

  const score = totalWeight > 0 ? hitWeight / totalWeight : 0;
  return { score, matched };
}

// ── Facet filtering ───────────────────────────────────────────────────────────

function passesFilter(b: VaultBuildingMeta, filter: VaultFacetFilter): boolean {
  if (filter.era && b.era !== filter.era) return false;
  if (filter.type && b.type !== filter.type) return false;
  if (filter.country && b.country?.toLowerCase() !== filter.country.toLowerCase()) return false;
  if (filter.facet && !b.facets.includes(filter.facet)) return false;
  return true;
}

// ── Query ─────────────────────────────────────────────────────────────────────

/** Query options. */
export interface VaultQueryOptions {
  filter?: VaultFacetFilter;
  /** Max results. Default 6. */
  limit?: number;
}

/**
 * Query the vault manifest with a free-text query + optional facet filters.
 * Returns buildings sorted by (textScore × DCS) descending.
 * With an empty query, returns all buildings sorted by DCS descending.
 */
export function queryVaultCorpus(
  manifest: VaultManifest,
  query: string,
  opts: VaultQueryOptions = {},
): VaultCorpusResult[] {
  const limit = opts.limit ?? 6;
  const filter = opts.filter ?? {};
  const queryTokens = tokenize(query);

  const results: VaultCorpusResult[] = [];

  for (const b of manifest.buildings) {
    if (!passesFilter(b, filter)) continue;

    const { score: textRel, matched } = textScore(b, queryTokens);
    if (queryTokens.length > 0 && textRel === 0) continue;

    // Composite: text relevance × capped DCS boost.
    const dcsCapped = Math.min(1.0, b.dcs);
    const composite = queryTokens.length > 0
      ? textRel * (0.6 + 0.4 * dcsCapped)
      : dcsCapped;

    results.push({ building: b, score: composite, matchedFields: matched });
  }

  results.sort((a, b) => b.score - a.score);
  return results.slice(0, limit);
}

/** Distinct era values across the manifest — for filter UI. */
export function vaultFacetValues(manifest: VaultManifest, facet: keyof VaultFacetFilter): string[] {
  const vals = new Set<string>();
  for (const b of manifest.buildings) {
    const v = b[facet as keyof VaultBuildingMeta];
    if (typeof v === "string" && v) vals.add(v);
  }
  return [...vals].sort();
}
